// <auto-generated />
namespace dancing_studio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Plans : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Plans));
        
        string IMigrationMetadata.Id
        {
            get { return "201512132007216_Plans"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
